version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    restart: always
    volumes:
      - .:/app/
      - /app/backend/node_modules
    env_file:
      - ./backend/.env.dev
    tty: true

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    restart: always
    volumes:
      - .:/app/
      - /app/frontend/node_modules
    tty: true
